# Generated by Django 4.1.5 on 2023-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_keydetails_cipher_text_alter_keydetails_phi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydetails',
            name='cipher_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keydetails',
            name='phi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keydetails',
            name='prime_multiple',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keydetails',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
