# Generated by Django 4.1.5 on 2023-02-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_keydetails_stego_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
