# Generated by Django 4.1.5 on 2023-02-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
