# Generated by Django 4.1.5 on 2023-02-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
