# Generated by Django 4.1.5 on 2023-02-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='length',
            field=models.TextField(blank=True, null=True),
        ),
    ]
